default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: backstore
  pool: 5
  username: root
  password: "root"

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  reconnect: false
  database: backstore
  pool: 5
  username: dbu
  password: "1234"
